### ISSUE TITLE
Wave discussion: Refine wave list from 681 and apply to Plan document

### ISSUE THREAD

**Issue by edburns** [jakartaee/jakartaee-platform#685]
Here is the Wave list from @JanWesterkamp-iJUG from #681 .

The (current) result for API dependencies (only):

Wave 1:

- Jakarta Activation
- Jakarta Annotation*
- Jakarta Authentication
- Jakarta EJB
- Jakarta EL
- Jakarta Lang Model
- Jakarta Inject
- Jakarta JSON
- Jakarta Persistence
- Jakarta Security
- Jakarta Servlet
- Jakarta Validation
- Jakarta REST
- Jakarta Websocket Client

Wave 2:

- Jakarta Authorization
- Jakarta Interceptor*
- Jakarta JMS
- Jakarta JSON Bind
- Jakarta Mail
- Jakarta Servlet JSP
- Jakarta Websocket
- Jakarta XMP Bind
- Jakarta XML SOAP

Wave 3:

- Jakarta CDI*
- Jakarta Servlet JSP JSTL
- Jakarta XML WS

Wave 4:

- Jakarta Batch
- Jakarta Concurrent
- Jakarta Transaction*
- Jakarta Platform Web Profile

Wave 5:

- Jakarta Faces*
- Jakarta Ressource

Wave 6:

- Jakarta Platform Web Profile*

Wave 7:

- Jakarta Platform*

*critical path

Let us use this issue to iterate the discussion and ultimately apply the work to https://github.com/jakartaee/jakartaee-platform/blob/gh-pages/jakartaee11/JakartaEE11ReleasePlan.md

[AB#6](https://dev.azure.com/jakarta-ee-azdo/7cf9a9d3-9854-41e0-9a66-99506a9ed874/_workitems/edit/6)

**Comment by edburns** [comment]
Here is the promised diff for discussion.

```diff
--- em-2529-waves-01-ivar.txt	2023-05-23 10:43:59
+++ em-2529-waves-02-jan.txt	2023-05-23 10:43:28
@@ -1,50 +1,54 @@
 Wave 1:
 
 Jakarta Activation
+Jakarta Annotation
+Jakarta Authentication
 Jakarta Bean Validation
 Jakarta Dependency Injection
+Jakarta Enterprise Beans
 Jakarta Expression Language
-Jakarta Interceptors
 Jakarta JSON Processing
-Jakarta SOAP with Attachments
+Jakarta Lang Model
+Jakarta Persistence
+Jakarta RESTful Web Services
+Jakarta Security
 Jakarta Servlet
-Jakarta WebSocket
+Jakarta Websocket Client
 
 Wave 2:
 
-Jakarta Authentication
 Jakarta Authorization
-Jakarta Debugging Support for Other Languages
+Jakarta Enterprise Web Services (XML SOAP?)
+Jakarta Interceptors
+Jakarta JMS
 Jakarta JSON Binding
 Jakarta Mail
 Jakarta Server Pages
-Jakarta XML Binding
+Jakarta Websocket
+Jakarta XML Binding (XMP Bind?)
 
 Wave 3:
 
 Jakarta Contexts and Dependency Injection
+Jakarta Standard Tag Library
 Jakarta XML Web Services
 
 Wave 4:
 
 Jakarta Batch
-Jakarta RESTful Web Services
+Jakarta Concurrent
+Jakarta EE Platform Web Profile
 Jakarta Transactions
 
 Wave 5:
 
-Jakarta Connectors
-Jakarta Enterprise Beans
-Jakarta Enterprise Web Services
-Jakarta Standard Tag Library
+Jakarta Resource
+Jakarta Server Faces
 
 Wave 6:
 
-Jakarta Security
-Jakarta Server Faces
+Jakarta EE Platform Web Profile
 
 Wave 7:
 
-Jakarta EE Platform Core Profile
 Jakarta EE Platform Full Platform
-Jakarta EE Platform Web Profile
```

**Comment by edburns** [comment]
[em-2529-waves-01-ivar.txt](https://github.com/jakartaee/jakartaee-platform/files/11545388/em-2529-waves-01-ivar.txt)
[em-2529-waves-02-jan.txt](https://github.com/jakartaee/jakartaee-platform/files/11545389/em-2529-waves-02-jan.txt)

**Comment by JanWesterkamp-iJUG** [comment]
Hello @edburns, which diagram you mean?

If you meant the mentioned separate issue for the jQA reports, this is created: #687 
I added reports for a lot of components specs and the separated TCKs I can found.

There are some issues, some could be solved by changing the wave of the API to one that fits the TCK too (i.e. Jakarta Validation). But some create a circular dependency, when the TCK is created with the API (i.e. Jakarta JSON Bind, Jakarta CDI)!

In general, a lot of the separated TCKs are created with a deviating environment compared to the corresponding API - this must be fixed!
As known already, APIs of component specs use a deviating environment than their umbrella spec and we have API dependencies to implementations and (outdated) test frameworks too.

May be, we should use the Jakarta Architecture Call in two weeks of discuss how to solve this?

I will be on JSail this week, so I can not promisse to make it to the call tomorrow, but I will try to...

**Comment by JanWesterkamp-iJUG** [comment]
@edburns, @arjantijms  Here is an update for the waves, derived from the CN4J Report results.

Note: 
PlantUML (operations research) does the job here now :-)
However, it shows the last possible wave for a component spec to release - instead of the possible first one before. 
Already separated TCKs of component specs and their dependencies taken into account - spec document dependencies not (yet).
To keep this operational, circular dependencies need to be prevented!

Wave 1:

* Jakarta Annotation

Wave 2:

* Jakarta EL
* Jakarta Interceptor
* Jakarta Inject
* Jakarta Lang Model (may be released with Jakarta CDI [Core] in wave 3)

Wave 3:

* Jakarta Activation
* Jakarta CDI [Core]
* Jakarta JSON
* Jakarta Transaction

Wave 4:

* Jakarta EJB
* Jakarta JSON Bind
* Jakarta Mail
* Jakarta Ressource
* Jakarta Servlet
* Jakarta Websocket Client
* Jakarta XMP Bind
* Jakarta XML SOAP

Wave 5:

* Jakarta Authorization
* Jakarta Batch
* Jakarta Persistence
* Jakarta REST
* Jakarta Servlet JSP
* Jakarta Validation
* Jakarta Websocket
* Jakarta XML WS

Wave 6:

* Jakarta Concurrent
* Jakarta JMS
* Jakarta Faces
* Jakarta Servlet JSP JSTL
* Jakarta Platform Core Profile (may be released with Jakarta Platform in last wave)

Wave 7:

* Jakarta Authentication
* Jakarta CDI Web (new)
* Jakarta Security

Wave 8:

* Jakarta Platform Web Profile (may be released with Jakarta Platform in last wave)
* Jakarta CDI Web (new)

Wave 9:

* Jakarta Platform

**Comment by JanWesterkamp-iJUG** [comment]
Alternatively, when the CDI TCK dependencies causing circular dependencies moved with their tests to the Jakarta Platform Web Profile and Jakarta Platform specs and all Jakarta Platform specs released together, the following changes apply:

...

Wave 6:

* Jakarta Authentication
* Jakarta Concurrent
* Jakarta JMS
* Jakarta Faces
* Jakarta Security
* Jakarta Servlet JSP JSTL

Wave 7:

* Jakarta Platform Core Profile
* Jakarta Platform Web Profile
* Jakarta Platform

**Comment by JanWesterkamp-iJUG** [comment]
Reviews welcome!

**Comment by hantsy** [comment]
What is Jakarta Resources and Jakarta CDI Web?

**Comment by edburns** [comment]
Jan and I are discussing this in AB#98.

**Comment by JanWesterkamp-iJUG** [comment]
> @JanWesterkamp-iJUG CDI API has references to things like Servlet (injecting HttpServletRequest) and transactions (injecting UserTransaction).

@arjantijms do you mean the API has references to Servlet and Transaction or the spec document?
The last would make sense, as older versions (3.x.y) had that dependencies before the clarification was done and the circular dependency with Transaction was removed (since 4.0.1).
So I can model them again, but reintroducing the circular dependency would make things worse. In the case of Servlet it could be tracked (if not solved/removed) - there is also a TCK dependency from REST here.
For the Transaction issue, we should remove it from the spec doc and also definitly make a (Major?) Release of Transaction to get rid of the circular dependency (to an old CDI version that again references CDI) - this was technical debt left from Jakarta EE 10 unfortunately.

**Comment by JanWesterkamp-iJUG** [comment]
> What is Jakarta Resources and Jakarta CDI Web?

@hantsy, Jakarta Resources is the artifact name in Maven for Jakarta Connectors, like Jakarta JMS is still in use for Jakarta Messaging - I updated the waves according to that for clarification.

Jakarta CDI Web is a splitted CDI for the Web Profile to extend the CDI Core (Profile) or currently called CDI Lite from the CDI "Full". For Details check @edburns comment and the follow up with @starksm64, who created an issue within CDI to track this:

https://github.com/jakartaee/cdi/issues/687

I created the speparated CDI Web and CDI Platform specs here especially to generate the wave contents and workaround the circular dependencies - the final solution depends on the ressources that could be invested on refactoring within the CDI spec team of course.

**Comment by JanWesterkamp-iJUG** [comment]
@edburns, as noted, there is an issue in jQA for handling package type "bundle", which leads to not showing dependencies when treated as type "jar".

Jakarta Security is updated now manually, which has some influence on the waves:

...
Wave 6:

- Jakarta Authentication
- Jakarta Concurrent
- Jakarta Messaging (Jakarta JMS in Maven)
- Jakarta Faces
- Jakarta Servlet JSP JSTL
- Jakarta Platform Core Profile (may be released with Jakarta Platform in last wave)

Wave 7:

- Jakarta CDI Web (new)
- Jakarta Security

Wave 8:

- Jakarta Platform Web Profile (may be released with Jakarta Platform in last wave)
- Jakarta CDI Platform (new)

Wave 9:

- Jakarta Platform

So, Jakarta Authentication moves from Wave 7 to Wave 6.
If a separate, new CDI Web spec is not created, then the CDI integration testing might be done in wave 7 may waves. The Platform/Profile specs could then be released together in wave 8.

**Comment by JanWesterkamp-iJUG** [comment]
I also updated the [CN4J Report here](https://github.com/jakartaee/jakartaee-platform/issues/687#issuecomment-1663274299).
